-- Tabla de Clientes para Baramovil
CREATE TABLE IF NOT EXISTS ADN_CLIENTES (
    CLT_CODIGO VARCHAR(10) PRIMARY KEY,
    CLT_NOMBRE VARCHAR(200) NOT NULL,
    CLT_RIF VARCHAR(20) NOT NULL,
    CLT_DIRECCION TEXT,
    CLT_TELEFONO VARCHAR(50),
    CLT_FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
